### ISSUE TITLE
Hard coded server

### ISSUE THREAD

**Issue by sthoen** [ITNG/SurveyGizmo#20]
I have noticed that line 75 of  surveygizmo / surveygizmo.py  has hard coded the REST server address. Unfortunately Survey Gizmo has other REST servers - in my case, I need to switch the Canadian server at https://restapica.surveygizmo.com  as the variable is not exposed to be changed, could we specify an overriding server in case it is needed.  I am aware that they have an EU server as well, but do not have the specific URL.

Thanks for this very handy library.

**Comment by rpkilby** [comment]
For now, the easy thing to do is to just override the `base_url`. eg,

```python
client = SurveyGizmo(...)
client.api.base_url = 'https://restapica.surveygizmo.com/'
```

**Comment by sthoen** [comment]
Thank you Ryan.

Sebastiaan

**Comment by rpkilby** [comment]
v1.2.3 should be up on PyPI. You should be able to pass `base_url` as a configurable parameter now. 

```python
client = SurveyGizmo(
    base_url='https://restapica.surveygizmo.com/',
    ...
)
```
