### ISSUE TITLE
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0) when calling client.api.survey.list()

### ISSUE THREAD

**Issue by arsirantala** [ITNG/SurveyGizmo#24]
Hiya,

When I'm trying to call
**client.api.survey.list()**

I get: 
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Full code:
client = SurveyGizmo(
    api_version='v5',

    # example token from SurveyGizmo docs
    api_token="E4F796932C2743FEBF150B421BE15EB9",
    api_token_secret="A9fGMkJ5pJF1k"
)

# Update client options through the config property.
client.config.api_token = KEY
client.config.api_token_secret = SECRET
client.config.base_url = "https://restapi.surveygizmo.eu/"
client.config.api_token = "head"

Any ideas what could be the issue? and how to fix the above code so listing of surveys would work?

Running the code in python 2.7 in Mac High Sierra.

Cheers

**Comment by arsirantala** [comment]
I actually found the reason - I had set the api_token twice accidentally :( this issue can be closed (and deleted if possible).

Sorry!

**Comment by rpkilby** [comment]
Ah, that makes sense. Thanks for the update!
