### ISSUE TITLE
Create a survey to a specific team

### ISSUE THREAD

**Issue by arsirantala** [ITNG/SurveyGizmo#25]
Sorry for this being surveygizmo api specific question, but maybe you could still shed some light how to use your module to define team parameter value in survey creation - I can see it takes 2 parameters in: survey text, survey type - I can also see a third parameter called kvargs. Can that be used to pass a dictionary containing in my case the team and its integer value?

**Comment by rpkilby** [comment]
> Sorry for this being surveygizmo api specific question

No problem! Feel free to ask any SurveyGizmo-related questions here.

> Can that be used to pass a dictionary containing in my case the team and its integer value?

Yes, you can pass arbitrary keyword arguments to the function, such as the team ID. These arguments are used to construct the API call, and you should use the name defined by the SurveyGizmo api (eg, `team`).

> I can also see a third parameter called kvargs. 

Based on your wording, it sounds like you're not familiar with argument packing/unpacking? If you are familiar, ignore this 😄, but if this is new to you, you can [read more about function arguments here](https://docs.python.org/3/tutorial/controlflow.html#more-on-defining-functions) (specifically, sections 4.7.3 and 4.7.4). If the docs aren't clear, there are tons of blogs/articles out there that explain the concept. Just google "python argument expansion" or "python argument packing"

**Comment by arsirantala** [comment]
Thank you! I was able to make survey questions now by using the suggested argument packing :)

But I faced a problem - in such type of case that survey question is a radio button, and one would like that the type of the radio button's value would of type other, and in that case a textbox would be shown beside the said radio button item, one would need to set this property:
properties[other]": "true"
If I try to pass this to kwargs, I get an error.

How would I solve this?

Here's my code related to this survey question:

```# Improvement priority: radio button with a list of options. Two options have an open text field for more details.
resp_create_surveyquestion = client.api.surveyquestion.create(survey_id, 1, type="radio", title="Improvement priority")
assert resp_create_surveyquestion["result_ok"] == True
print "Survey question (type: %s) was succesfully added with id: %s" % (resp_create_surveyquestion[u"data"][u"_subtype"], resp_create_surveyquestion[u"data"][u"id"])
my_logger.info("Survey question (type: %s) was succesfully added with id: %s" % (resp_create_surveyquestion[u"data"][u"_subtype"], resp_create_surveyquestion[u"data"][u"id"]))

question_id = resp_create_surveyquestion[u"data"][u"id"]
for i in range(0, 7):
    if i == 0:
        resp_create_surveyquestion = client.api.surveyoption.create(survey_id, question_id, "Very High", str(i))
    elif i == 1:
        resp_create_surveyquestion = client.api.surveyoption.create(survey_id, question_id, "High", str(i))
    elif i == 2:
        resp_create_surveyquestion = client.api.surveyoption.create(survey_id, question_id, "Moderate", str(i))
    elif i == 3:
        resp_create_surveyquestion = client.api.surveyoption.create(survey_id, question_id, "Normal", str(i))
    elif i == 4:
        resp_create_surveyquestion = client.api.surveyoption.create(survey_id, question_id, "Low", str(i))
    elif 5 <= i <= 6:
        if i == 5:
            resp_create_surveyquestion = client.api.surveyoption.create(survey_id, question_id, "Other", str(i), properties[other]="true")
        else:
            resp_create_surveyquestion = client.api.surveyoption.create(survey_id, question_id, "Other 2", str(i), properties[other]="true")


    assert resp_create_surveyquestion["result_ok"] == True
    print "Survey option (type: %s) was succesfully added with id: %s" % (resp_create_surveyquestion[u"data"][u"_type"], resp_create_surveyquestion[u"data"][u"id"])
    my_logger.info("Survey question (type: %s) was succesfully added with id: %s" % (resp_create_surveyquestion[u"data"][u"_type"], resp_create_surveyquestion[u"data"][u"id"]))```

**Comment by rpkilby** [comment]
Unfortunately, this was an oversight when I first wrote the package. Unpacked arguments must be valid python identifiers, and `properties[other]` is invalid. See #23 for related discussion.
